apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: dlacofbs/article1_vue:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VITE_KAKAO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: VITE_KAKAO_API_KEY
            - name: VITE_KAKAO_REST_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: VITE_KAKAO_REST_API_KEY